on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Attempt Release 1
        uses: zacck/test-action@v0.1.1
        with: 
          secret_input: ${{ secrets.OPENFN_API_KEY }}
